
[build]
  base = "frontend"          # Tera React/Vite project folder
  publish = "dist"           # Vite build output folder
  command = "npm run build"  # Build command

[dev]
  framework = "vite"
